#include QMK_KEYBOARD_H

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
edit * edit it directly.
 */

#define L_UP KC_Q
#define L_UR KC_W
#define L_UM KC_F
#define L_UI KC_P
#define L_U2 KC_B
#define R_U2 KC_J
#define R_UI KC_L
#define R_UM KC_U
#define R_UR KC_Y
#define R_UP KC_SCLN
#define L_HP KC_A
#define L_HR KC_R
#define L_HM KC_S
#define L_HI KC_T
#define L_H2 KC_G
#define R_H2 KC_M
#define R_HI KC_N
#define R_HM KC_E
#define R_HR KC_I
#define R_HP KC_O
#define L_LP KC_Z
#define L_LR KC_X
#define L_LM KC_C
#define L_LI KC_D
#define L_L2 KC_V
#define R_L2 KC_K
#define R_LI KC_H
#define R_LM KC_COMM
#define R_LR KC_DOT
#define R_LP KC_SLSH
#define L_T0 KC_TAB
#define L_T1 KC_SPC
#define R_T0 KC_ENT
#define R_T1 KC_BSPC

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_split_3x5_2(
          L_UP, L_UR, L_UM, L_UI, L_U2, R_U2, R_UI, R_UM, R_UR, R_UP,
          L_HP, L_HR, L_HM, L_HI, L_H2, R_H2, R_HI, R_HM, R_HR, R_HP,
          L_LP, L_LR, L_LM, L_LI, L_L2, R_L2, R_LI, R_LM, R_LR, R_LP,
                            L_T0, L_T1, R_T0, R_T1
      )
};

