#include QMK_KEYBOARD_H


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

#define L_UP KC_Z
#define L_UR KC_W
#define L_UM KC_F
#define L_UI KC_P
#define L_U2 KC_COMM
#define R_U2 KC_DOT
#define R_UI KC_L
#define R_UM KC_U
#define R_UR KC_Y
#define R_UP KC_SCLN
#define L_HP KC_A
#define L_HR KC_R
#define L_HM KC_S
#define L_HI KC_T
#define L_H2 KC_G
#define R_H2 KC_M
#define R_HI KC_N
#define R_HM KC_E
#define R_HR KC_I
#define R_HP KC_O
#define L_LP KC_Q
#define L_LR KC_X
#define L_LM KC_C
#define L_LI KC_D
#define L_L2 KC_V
#define R_L2 KC_K
#define R_LI KC_H
#define R_LM OSM(MOD_RGUI)
#define R_LR OSM(MOD_RALT)
#define R_LP OSM(MOD_RCTL)
#define L_T0 OSL(1)
#define L_T1 KC_SPC
#define R_T1 OSM(MOD_RSFT)
#define R_T0 OSL(2)

#include "g/keymap_combo.h"

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT(
          L_UP, L_UR, L_UM, L_UI, L_U2,     R_U2, R_UI, R_UM, R_UR, R_UP,
          L_HP, L_HR, L_HM, L_HI, L_H2,     R_H2, R_HI, R_HM, R_HR, R_HP,
          L_LP, L_LR, L_LM, L_LI, L_L2,     R_L2, R_LI, R_LM, R_LR, R_LP,
                            L_T0, L_T1,     R_T1, R_T0
      ),
	[1] = LAYOUT(
                 _______, _______, KC_UP,   _______, KC_COMM,      KC_DOT,    KC_7,   KC_8,   KC_9, _______,
           OSM(MOD_LSFT), KC_LEFT, KC_DOWN, KC_RGHT, _______,     _______,    KC_4,   KC_5,   KC_6, _______,
OSM(MOD_LCTL), OSM(MOD_LALT), OSM(MOD_LGUI),_______, _______,        KC_0,    KC_1,   KC_2,   KC_3, _______,
                                            _______, _______,     _______,    _______
      ),
	[2] = LAYOUT(
                 _______, _______, KC_UP,   _______, KC_COMM,      KC_DOT,    KC_AMPR,   KC_ASTR,   KC_LPRN,_______,
           OSM(MOD_LSFT), KC_LEFT, KC_DOWN, KC_RGHT, _______,     _______,    KC_DLR,    KC_PERC,   KC_CIRC,_______,
OSM(MOD_LCTL), OSM(MOD_LALT), OSM(MOD_LGUI),_______, _______,     KC_QUES,    KC_EXLM,   KC_AT,     KC_HASH,  _______,
                                            _______, _______,     _______,    _______
      )
};

//	[0] = LAYOUT_split_3x5_2(
//	KC_Q, KC_W, KC_F, KC_P, KC_B, KC_J, KC_L, KC_U, KC_Y, KC_QUOT,
//	KC_A, KC_R, KC_S, KC_T, KC_G, KC_M, KC_N, KC_E, KC_I, KC_O,
//	KC_Z, KC_X, KC_C, KC_D, KC_V, KC_K, KC_H, KC_RGUI, KC_RALT, KC_RCTL,
//	TO(1), KC_SPC, KC_RSFT, KC_NO),
//	[1] = LAYOUT_split_3x5_2(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_7, KC_8, KC_9, KC_NO,
//	KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_4, KC_5, KC_6, KC_NO,
//	KC_LCTL, KC_LALT, KC_LGUI, KC_NO, KC_NO, KC_NO, KC_1, KC_2, KC_3, KC_NO,
//	TO(0), KC_NO, KC_TRNS, KC_0)

