#define L_UP KC_Q
#define L_UR KC_W
#define L_UM KC_F
#define L_UI KC_P
#define L_U2 KC_B
#define R_U2 KC_J
#define R_UI KC_L
#define R_UM KC_U
#define R_UR KC_Y
#define R_UP KC_SCLN
#define L_HP KC_A
#define L_HR KC_R
#define L_HM KC_S
#define L_HI KC_T
#define L_H2 KC_G
#define R_H2 KC_M
#define R_HI KC_N
#define R_HM KC_E
#define R_HR KC_I
#define R_HP KC_O
#define L_LP KC_Z
#define L_LR KC_X
#define L_LM KC_C
#define L_LI KC_D
#define L_L2 KC_V
#define R_L2 KC_K
#define R_LI KC_H
#define R_LM OSM(MOD_RGUI)
#define R_LR OSM(MOD_RALT)
#define R_LP OSM(MOD_RCTL)
#define L_T0 OSL(1)
#define L_T1 KC_SPC
#define R_T1 OSM(MOD_RSFT)
#define R_T0 OSL(2)